services:
  - type: web
    name: car-bike-rental
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: spring.mongodb.uri
        sync: false
      - key: spring.mongodb.database
        value: rental_db